apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: rust-test-target
spec:  
  components:
  - name: mock
    properties:
      foo: bar2    
  forceRedeploy: true
  topologies:
  - bindings:
    - role: instance
      provider: providers.target.rust
      config:
        name: "rust-lib"
        libFile: "/etc/symphony-api/extensions/libmock.so"
        libHash: "<hash>"