apiVersion: fabric.symphony/v1
kind: Target
metadata:
  name: rust-test-target
spec:  
  components:
  - name: mock
    properties:
      foo: bar
  forceRedeploy: true
  topologies:
  - bindings:
    - role: instance
      provider: providers.target.rust
      config:
        name: "rust-lib"
        libFile: "pkg/apis/v1alpha1/providers/target/rust/target/release/libmock.so"
        libHash: "26e68667de3d7bfd5ff758191ce4a231800a93f52e1751c10fa0afc7811893cd"